### ISSUE TITLE
Cannot update to Stoneblock 1.4.3

### ISSUE THREAD

**Issue by Panderine** [Domaman202/ATLauncher-Crack#14]
**Describe the bug**
ATLauncher show a message saying there is a new modpack version. When I try to update it fails. Console shows this log:

```
[12/12/2022 14:11:32 p. m.] Started install of FTB StoneBlock 3 version 1.4.3
[12/12/2022 14:11:32 p. m.] com.atlauncher.network.DownloadException: https://api.atlauncher.com/v1/launcher/forge-version/40.1.84 request wasn't successful: Response{protocol=h2, code=403, message=, url=https://api.atlauncher.com/v1/launcher/forge-version/40.1.84}
[12/12/2022 14:11:32 p. m.] 	at com.atlauncher.network.Download.execute(Download.java:321)
[12/12/2022 14:11:32 p. m.] 	at com.atlauncher.network.Download.asTypeWithThrow(Download.java:175)
[12/12/2022 14:11:32 p. m.] 	at com.atlauncher.network.Download.asType(Download.java:182)
[12/12/2022 14:11:32 p. m.] 	at com.atlauncher.network.Download.asType(Download.java:196)
[12/12/2022 14:11:32 p. m.] 	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromModpacksCh(InstanceInstaller.java:843)
[12/12/2022 14:11:32 p. m.] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:308)
[12/12/2022 14:11:32 p. m.] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:143)
[12/12/2022 14:11:32 p. m.] 	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
[12/12/2022 14:11:32 p. m.] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[12/12/2022 14:11:32 p. m.] 	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
[12/12/2022 14:11:32 p. m.] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12/12/2022 14:11:32 p. m.] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12/12/2022 14:11:32 p. m.] 	at java.base/java.lang.Thread.run(Thread.java:833)
[12/12/2022 14:11:32 p. m.] com.atlauncher.network.DownloadException: https://api.atlauncher.com/v1/launcher/forge-version/40.1.84 request wasn't successful: Response{protocol=h2, code=403, message=, url=https://api.atlauncher.com/v1/launcher/forge-version/40.1.84}

	at com.atlauncher.network.Download.execute(Download.java:321)

	at com.atlauncher.network.Download.asTypeWithThrow(Download.java:175)

	at com.atlauncher.network.Download.asType(Download.java:182)

	at com.atlauncher.network.Download.asType(Download.java:196)

	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromModpacksCh(InstanceInstaller.java:843)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:308)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:143)

	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

	at java.base/java.lang.Thread.run(Thread.java:833)

[12/12/2022 14:11:32 p. m.] java.lang.NullPointerException: Cannot invoke "com.atlauncher.data.APIResponse.getData()" because "forgeVersionInfo" is null
[12/12/2022 14:11:32 p. m.] 	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromModpacksCh(InstanceInstaller.java:848)
[12/12/2022 14:11:32 p. m.] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:308)
[12/12/2022 14:11:32 p. m.] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:143)
[12/12/2022 14:11:32 p. m.] 	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
[12/12/2022 14:11:32 p. m.] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[12/12/2022 14:11:32 p. m.] 	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
[12/12/2022 14:11:32 p. m.] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12/12/2022 14:11:32 p. m.] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12/12/2022 14:11:32 p. m.] 	at java.base/java.lang.Thread.run(Thread.java:833)
[12/12/2022 14:11:32 p. m.] java.lang.NullPointerException: Cannot invoke "com.atlauncher.data.APIResponse.getData()" because "forgeVersionInfo" is null

	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromModpacksCh(InstanceInstaller.java:848)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:308)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:143)

	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by Panderine** [comment]
The same issue happens when creating a clean forge instance

**Comment by Domaman202** [comment]
this is again some problems of the original ATL, I do not do this, sorry
