### ISSUE TITLE
"Error Getting Versions"

### ISSUE THREAD

**Issue by xPixelated** [Domaman202/ATLauncher-Crack#22]
**Describe the bug**
"Error Getting Versions" on Loader Versions.

**To Reproduce**
1. Go to Vanilla Packs
2. Click on any Loader
3. Loader Version: Error Getting Versions

**Logs**
[02/03/2023 23:10:54 PM] Error fetching loading versions
[02/03/2023 23:10:54 PM] com.apollographql.apollo.exception.ApolloHttpException: HTTP 403 
[02/03/2023 23:10:54 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:108)
[02/03/2023 23:10:54 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
[02/03/2023 23:10:54 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:114)
[02/03/2023 23:10:54 PM] 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[02/03/2023 23:10:54 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[02/03/2023 23:10:54 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[02/03/2023 23:10:54 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[02/03/2023 23:10:54 PM] com.apollographql.apollo.exception.ApolloHttpException: HTTP 403 
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:108)
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:114)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Screenshots**
![image](https://user-images.githubusercontent.com/98027192/216638992-fea4bc1e-f5a3-4b4f-ac71-f2b670e361a8.png)

- OS: Windows 10
- Java Version: Java 8, 16, & 18

I don't how am I able to fix it, but if the problem is from the original ATlauncher, please let me know.

**Comment by Panderine** [comment]
I belive ATLauncher goes through some of their own servers in order to get the forge versions. Try to visit https://atlauncher.com/ and check if you can reach it or you have been ip banned from their web server.

**Comment by xPixelated** [comment]
> 
The Website works fine for me
![image](https://user-images.githubusercontent.com/98027192/217411765-06fdda40-3d0b-44c0-985a-8fe12aa5aba4.png)

**Comment by Panderine** [comment]
They fixed the ban to only affect the apis now. Apparently if you use a forked version you still go through their APIs to download forge or any other loader. Try using a VPN and it would work until they ban you again.

**Comment by xPixelated** [comment]
> They fixed the ban to only affect the apis now. Apparently if you use a forked version you still go through their APIs to download forge or any other loader. Try using a VPN and it would work until they ban you again.

Oof still didn't work. :(
Edit: But another thing is I can still change the fabric version from my current instance, but creating an instance, its not working. 
![image](https://user-images.githubusercontent.com/98027192/217499085-1078c50b-e55b-4789-8512-e1aec1c6957f.png)

**Comment by Gatitomono47** [comment]
set in network settings disable http/2? it worked for me

**Comment by xPixelated** [comment]
> 

Its already disabled, and still.. ;-;

**Comment by Panderine** [comment]
try with the official ATLauncher and see if you can populate those dropbox

**Comment by xPixelated** [comment]
> try with the official ATLauncher and see if you can populate those dropbox

It works fine from the official Launcher

![image](https://user-images.githubusercontent.com/98027192/218247227-1624c4f0-513c-4a1e-8fbb-e3d3a195d484.png)
![image](https://user-images.githubusercontent.com/98027192/218247248-234f5109-08dc-4314-bd12-8fd766341b60.png)

**Comment by User-green** [comment]
#26
