### ISSUE TITLE
Error on GraphQL Query & Unknown Source (It happened again)

### ISSUE THREAD

**Issue by nightbright199** [Domaman202/ATLauncher-Crack#34]
### What happened?

1. Open TLauncher (Already causes an error)
2. Install a modpack (Another same error but with longer logs)

Expectation: Work fine

### Operating System

Windows

### Relevant log output

```shell
Step 1:
[14/06/2023 17:32:39 PM] Error on GraphQL query
[14/06/2023 17:32:39 PM] com.apollographql.apollo.exception.ApolloHttpException: HTTP 403 
[14/06/2023 17:32:39 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:108)
[14/06/2023 17:32:39 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
[14/06/2023 17:32:39 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:114)
[14/06/2023 17:32:39 PM] 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[14/06/2023 17:32:39 PM] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14/06/2023 17:32:39 PM] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14/06/2023 17:32:39 PM] 	at java.lang.Thread.run(Unknown Source)
[14/06/2023 17:32:39 PM] com.apollographql.apollo.exception.ApolloHttpException: HTTP 403 
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:108)
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:114)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


Step 2:
[14/06/2023 17:25:41 PM] Error on GraphQL query
[14/06/2023 17:25:41 PM] com.apollographql.apollo.exception.ApolloHttpException: HTTP 403 
[14/06/2023 17:25:41 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:108)
[14/06/2023 17:25:41 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
[14/06/2023 17:25:41 PM] 	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:114)
[14/06/2023 17:25:41 PM] 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
[14/06/2023 17:25:41 PM] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14/06/2023 17:25:41 PM] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14/06/2023 17:25:41 PM] 	at java.lang.Thread.run(Unknown Source)
[14/06/2023 17:25:41 PM] com.apollographql.apollo.exception.ApolloHttpException: HTTP 403 
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:108)
	at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
	at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:114)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[14/06/2023 17:25:41 PM] java.lang.NullPointerException
[14/06/2023 17:25:41 PM] 	at com.atlauncher.data.minecraft.loaders.fabric.FabricLoader.getMainClass(FabricLoader.java:153)
[14/06/2023 17:25:41 PM] 	at com.atlauncher.workers.InstanceInstaller.determineMainClass(InstanceInstaller.java:2390)
[14/06/2023 17:25:41 PM] 	at com.atlauncher.workers.InstanceInstaller.install(InstanceInstaller.java:2116)
[14/06/2023 17:25:41 PM] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:363)
[14/06/2023 17:25:41 PM] 	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:148)
[14/06/2023 17:25:41 PM] 	at javax.swing.SwingWorker$1.call(Unknown Source)
[14/06/2023 17:25:41 PM] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[14/06/2023 17:25:41 PM] 	at javax.swing.SwingWorker.run(Unknown Source)
[14/06/2023 17:25:41 PM] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14/06/2023 17:25:41 PM] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14/06/2023 17:25:41 PM] 	at java.lang.Thread.run(Unknown Source)
[14/06/2023 17:25:41 PM] java.lang.NullPointerException
	at com.atlauncher.data.minecraft.loaders.fabric.FabricLoader.getMainClass(FabricLoader.java:153)
	at com.atlauncher.workers.InstanceInstaller.determineMainClass(InstanceInstaller.java:2390)
	at com.atlauncher.workers.InstanceInstaller.install(InstanceInstaller.java:2116)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:363)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:148)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

### Additional Information

https://paste.atlauncher.com/view/f5ab912b-a6b2-446e-9400-0a4823b2e4cb

### Is this actually a launcher bug?

- [X] I am sure this is a bug with the launcher and not an issue with running Minecraft

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Domaman202** [comment]
![image](https://github.com/Domaman202/ATLauncher-Crack/assets/51743763/83961745-f972-4bae-bb78-d7cc92a68ef6)

**Comment by Domaman202** [comment]
Jokes of the official launcher, I still don’t understand why this is happening, on the site my ip was banned for the umpteenth time

**Comment by Domaman202** [comment]
![image](https://github.com/Domaman202/ATLauncher-Crack/assets/51743763/412acbb1-ab9a-443b-9ef6-73119bd5eca0)

**Comment by nightbright199** [comment]
ah damn, at least i found an alt launcher now. SKLauncher, it has skin support and cracked support, it seems like they're working on mod manager too

**Comment by Domaman202** [comment]
Check new readme.md
